SELECT 
    SUM(CASE WHEN FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'BASS') THEN 1
             WHEN FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME = 'SNAPPER') THEN 1
             ELSE 0 END) AS FISH_COUNT
FROM FISH_INFO;
